language: node_js
os: linux
dist: bionic

node_js:
- "8"
- "10"
- "12"
- "stable"

script:
- "npm run test:cov"

after_script:
- "npm i -g codecov.io && cat ./coverage/lcov.info | codecov"

# run tests without coverage on node.js 6, since nyc requires node 8
jobs:
  include:
    - node_js: "6"
      script: "npm run test"
